### ISSUE TITLE
Unable to open curve fitting interface

### ISSUE THREAD

**Issue by tedzards509** [Sjoerd1993/Graphs#674]
In the recent beta published to Flathub, when after opening the following csv: 
```
;m in kg;\Delta m in kg;F_G in N;\Delta F_G in N;s‘ in m ;\Delta s* in m;s = (s‘*L)/L‘ in m;\Delta s in m ;Steigung a in ;\Delta a in ;E in Pa;\Delta E in Pa
;0,0492;0,0002;0,4827;0,0020;0;0,001;0,0000;0,0003;;;;
;0,1042;0,0002;1,0222;0,0020;0,007;0,001;0,0021;0,0004;;;;
;0,1492;0,0002;1,4637;0,0020;0,012;0,001;0,0035;0,0004;;;;
;0,1990;0,0002;1,9522;0,0020;0,018;0,001;0,0053;0,0004;;;;
;0,2484;0,0002;2,4368;0,0020;0,025;0,001;0,0073;0,0004;;;;
;0,2990;0,0002;2,9332;0,0020;0,030;0,001;0,0088;0,0004;;;;
;0,3486;0,0002;3,4198;0,0020;0,037;0,001;0,0108;0,0004;;;;
;0,3982;0,0002;3,9063;0,0020;0,043;0,001;0,0126;0,0004;;;;
;;;;;;;;;;;;
;;;;;;;;;;;;
;L in m;\Delta L in m;;;;;;;;;;
;0,8;0,002;;;;;;;;;;
```
(Skip 1 row, ; delimiters, , for decimal, X row 3, Y row 7)

And trying to open the curve fitting dialog, I get the following error:
```
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/graphs/item_box.py", line 90, in curve_fitting
    CurveFittingWindow(self.get_application(), self.props.item)
  File "/app/lib/python3.11/site-packages/graphs/curve_fitting.py", line 68, in __init__
    self.fit_curve()
  File "/app/lib/python3.11/site-packages/graphs/curve_fitting.py", line 229, in fit_curve
    min(self.data_curve.xdata), max(self.data_curve.xdata), 5000,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'NoneType' and 'float'
```

I could see its because of the comments below the data.

**Comment by Sjoerd1993** [comment]
I think it's the same issue as #675 indeed. Will take a look into this.

**Comment by Sjoerd1993** [comment]
Found the issue here (as well with #675). Basically some of the comments on the bottom did  not raise an error when parsing as float, but returned `None` instead. Fixed this now in a local branch, but want to make a few more tweaks before setting up a PR.
