### ISSUE TITLE
Error: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by sophie-h** [Sjoerd1993/Graphs#691]
Not sure how I triggered this but maybe it's obvious from the code if there is messing a check or something

```
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/matplotlib/cbook.py", line 298, in process
    func(*args, **kwargs)
  File "/app/lib/python3.11/site-packages/graphs/canvas.py", line 674, in drag_pan
    self.ax_drag_pan(ax, self._pan_info.button, event.key, event.x,
  File "/app/lib/python3.11/site-packages/graphs/canvas.py", line 697, in ax_drag_pan
    ylim = points[:, 1]
           ~~~~~~^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

**Comment by Sjoerd1993** [comment]
I've noticed this before in the command output, have tried to find the source at one point but couldn't find it directly, nor does it seem to affect anything.

Either way good to have the issue up, as it's easy to forget about these less consequential errors.
